version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: spark_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "outside:${HOST_IP}"
    networks: 
      - spark-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: spark_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: spark_zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://spark_kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "outside:${HOST_IP}"
    networks:
      - spark-network
networks:
    spark-network:
      external:
        name: 24_spark-network
